# Generated by Django 4.0.3 on 2022-04-02 10:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ElectronicStore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='order_update',
            name='order',
        ),
        migrations.AddField(
            model_name='product',
            name='Specifications',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 10, 16, 25, 822893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_update',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 10, 16, 25, 822893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_update',
            name='update_desc',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On the Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='pending', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(default='', upload_to='products'),
        ),
        migrations.CreateModel(
            name='Delivery_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=90)),
                ('Email', models.CharField(max_length=111)),
                ('Address', models.CharField(max_length=111, null=True)),
                ('City', models.CharField(max_length=111)),
                ('State', models.CharField(max_length=111)),
                ('Zip_code', models.CharField(default=0, max_length=111, null=True)),
                ('phonenumber', models.IntegerField(default=1, max_length=111, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='Cust_Address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ElectronicStore.delivery_address'),
        ),
    ]
