# Generated by Django 4.0.3 on 2022-03-14 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 9, 9, 30, 382946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_update',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 14, 9, 9, 30, 384940, tzinfo=utc)),
        ),
    ]
