# Generated by Django 4.0.3 on 2022-03-14 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicStore', '0002_alter_order_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 9, 11, 9, 725248, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_update',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 14, 9, 11, 9, 726245, tzinfo=utc)),
        ),
    ]
