# Generated by Django 4.0.3 on 2022-04-02 10:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicStore', '0002_remove_customer_email_remove_order_update_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_update',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ElectronicStore.delivery_address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 10, 21, 37, 104494, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_update',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 10, 21, 37, 104494, tzinfo=utc)),
        ),
    ]
