# Generated by Django 4.0.3 on 2022-03-15 06:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicStore', '0003_alter_order_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Specifications',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 6, 1, 57, 238805, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_update',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 15, 6, 1, 57, 239802, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_update',
            name='update_desc',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On the Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='pending', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(max_length=10000),
        ),
    ]
