# Generated by Django 4.0.3 on 2022-03-18 05:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicStore', '0004_product_specifications_alter_order_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 5, 50, 11, 78292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_update',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 18, 5, 50, 11, 79288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(default='', upload_to='products'),
        ),
    ]
