# Generated by Django 4.0.3 on 2022-04-02 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicStore', '0007_alter_delivery_address_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_address',
            name='Address',
            field=models.CharField(default='Balaju', max_length=111),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='Date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 12, 37, 30, 615075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_update',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 12, 37, 30, 616073, tzinfo=utc)),
        ),
    ]
