# Generated by Django 4.0.3 on 2022-04-02 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicStore', '0011_remove_delivery_address_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_address',
            name='Zip_code',
        ),
        migrations.RemoveField(
            model_name='delivery_address',
            name='phonenumber',
        ),
        migrations.AlterField(
            model_name='order',
            name='Date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 13, 10, 53, 813447, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_update',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 13, 10, 53, 814445, tzinfo=utc)),
        ),
    ]
