# Generated by Django 4.0.3 on 2022-04-03 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicStore', '0013_delivery_address_phone_number_alter_order_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_update',
            name='customer',
        ),
        migrations.AlterField(
            model_name='order',
            name='Date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 7, 43, 53, 944916, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_update',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 3, 7, 43, 53, 945916, tzinfo=utc)),
        ),
    ]
