# Generated by Django 4.0.3 on 2022-04-03 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicStore', '0014_remove_order_update_customer_alter_order_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_update',
            name='Customer_Name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 7, 55, 50, 617510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_update',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 3, 7, 55, 50, 617510, tzinfo=utc)),
        ),
    ]
