# Generated by Django 4.0.3 on 2022-04-05 07:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicStore', '0019_alter_order_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_update',
            name='payment_complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order_update',
            name='payment_method',
            field=models.CharField(choices=[('Cash on devliery', 'Cash on delivery'), ('Khalti', 'Khalti')], default='Cash on Devliery', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 7, 52, 26, 523191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_update',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 5, 7, 52, 26, 523191, tzinfo=utc)),
        ),
    ]
