# Generated by Django 4.0.3 on 2022-04-10 07:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicStore', '0020_order_update_payment_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 7, 40, 14, 279186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_update',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 7, 40, 14, 279186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_update',
            name='update_desc',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On the Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Accepted', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('G', 'Gaming')], max_length=50),
        ),
    ]
