# Generated by Django 4.0.3 on 2022-04-18 06:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicStore', '0023_alter_order_update_ordered_date_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=500)),
                ('Email', models.CharField(default='', max_length=500)),
                ('Phone', models.IntegerField(default=10)),
                ('Feedback', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='order_update',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 18, 6, 2, 17, 995157, tzinfo=utc)),
        ),
    ]
